# nixpacks.toml
[phases.setup]
nixPkgs = ['python311', 'ffmpeg']

[phases.build]
nixPkgs = ['python311', 'ffmpeg']

[phases.install]
nixPkgs = ['python311', 'ffmpeg']

[staticAssets]
# No static assets

[start]
cmd = "python main.py"
